"""Bronze asset.

This file was generated by `polster add-asset`.
"""

from dagster import asset

from core.bronze_hr_employees import extract
from orchestration.utils import create_output_with_metadata


@asset(
    group_name="bronze",
    description="Bronze asset for hr_employees",
    compute_kind="polars",
)
def run_bronze_hr_employees():
    """Run bronze extraction for hr_employees."""
    bronze_path, df, metadata = extract()
    return create_output_with_metadata(bronze_path, df, metadata)
