"""Bronze asset.

This file was generated by `polster add-asset`.
"""

from dagster import asset

from core.bronze_fin_general_ledger import extract
from orchestration.utils import create_output_with_metadata


@asset(
    group_name="bronze",
    description="Bronze asset for fin_general_ledger",
    compute_kind="polars",
)
def run_bronze_fin_general_ledger():
    """Run bronze extraction for fin_general_ledger."""
    bronze_path, df, metadata = extract()
    return create_output_with_metadata(bronze_path, df, metadata)
