"""Bronze layer data extraction.

This file was generated by `polster add-asset`. Implement your extract() function
to process data and write it to the bronze layer.
"""

from __future__ import annotations

from datetime import datetime

import polars as pl

try:
    # Try relative imports (when run as module through Dagster)
    from .storage import write_parquet
except ImportError:
    # Fall back to absolute imports (when run directly)
    import sys
    import os

    # Add src directory to path for absolute imports
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
    from core.storage import write_parquet


def extract() -> tuple[str, pl.DataFrame, dict]:
    """Extract data and write to bronze layer.

    Returns:
        tuple[str, pl.DataFrame, dict]: Tuple containing:
            - Path to the written parquet file
            - DataFrame with extracted data
            - Metadata dictionary with row count, columns, etc.
    """
    # TODO: Uncomment and modify this example implementation with your actual data extraction logic
    #
    # # Create sample data (replace with your actual data source)
    # df = pl.DataFrame({
    #     "id": [1, 2, 3],
    #     "name": ["Alice", "Bob", "Charlie"],
    #     "value": [10.5, 20.3, 15.7],
    #     "created_at": ["2024-01-01", "2024-01-02", "2024-01-03"]
    # })
    #
    # # Add metadata
    # df = df.with_columns(
    #     pl.lit(datetime.utcnow().isoformat()).alias("fetched_at")
    # )
    #
    # # Write with timestamp
    # timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    # output_path = write_parquet(df, "bronze", f"bronze_fin_general_ledger_{timestamp}.parquet")
    #
    # # Prepare metadata for Dagster
    # metadata = {
    #     "row_count": len(df),
    #     "columns": list(df.columns),
    #     "dtypes": {col: str(dtype) for col, dtype in zip(df.columns, df.dtypes)},
    # }
    #
    # return output_path, df, metadata
    #
    # Note: Uncomment the above code and modify it for your use case

    pass  # TODO: Replace with your implementation and remove this pass statement


if __name__ == "__main__":
    extract()
